### ISSUE TITLE
Examples use faulty error handling

### ISSUE THREAD

**Issue by mdparker** [o3o/bindbc-raylib#3]
Hi! I notice in your examples that you're only checking for `RaylibSupport.badLibrary`. Because of this, the `else` branch will run even when the load function returns `noLibrary`. I see that your loader is properly returning that when no library is found, so it's a possibility when your users misconfigure the library (like compiling for 64-bit but attempting to load a 32-bit dll).

The proper way to check for errors BindBC style is:

```d
// Option 1
// I've configured my minimum required version at compile time,
// so any failure here means bailing out
if(retVal != raylibSupport) 
    errorOut();

// Option 2
// I've configured my preferred version at compile time,
// but I can run with a specific lower version
if(retVal == RaylibSupport.noLibrary || loadedRaylibVersion () < myMinimumRequiredVersion)
    errorOut();

// Option 3
// I've configured my preferred version at compile time, 
// but I can run with any version of the library. Only bail out 
// when no library was loaded at all
if(retVal == RaylibSupport.noLibrary || loadedRaylibVersion == RaylibSupport.noLibrary) 
    errorOut();
```

The purpose of `badLibrary` is to indicate that *some* version of the library may have loaded successfully, but it wasn't the one configured at compile time. Sometimes users may want to configure support for a higher version of a library and use a newer feature if it's available, but will still be happy to run if a lower version of the library loads. 

Unfortunately, in your loader I see you're setting `loadedVersion` to `badLibrary` when a specific version fails to load, so it's currently not possible with this binding to use a lower library version. And the return value of your `loadedRaylibVersion` is meaningless in that case, as it will always match the compile-time configured version. For it to be in line with the intent of the BindBC error handling API, lines like this:

```d
if (errorCount() != errCount) {
    loadedVersion = RaylibSupport.badLibrary;
 } else {
    loadedVersion = RaylibSupport.raylib250;
}
```

Should be changed to:

```d
if (errorCount() != errCount) {
    return RaylibSupport.badLibrary;
 } else {
    loadedVersion = RaylibSupport.raylib250;
}
```
Then if 3.0.0 fails to load because the user has a 2.5.0 dll, the show can still go on if the 2.5.0 features are acceptable.

Anyway, your examples should probably just use the first option I listed above and bail out on any failure, as I assume they'll be configured to the specific version that has the features you want to demo.

**Comment by o3o** [comment]
Illuminating as always! 
Thank you for your suggestion (and for your great work in D community)

**Comment by mdparker** [comment]
Thanks for the kind words. And sorry for the typo on the Option 3 error handling! `!=` should be `==`. (I've edited it).
