### ISSUE TITLE
badLibrary error

### ISSUE THREAD

**Issue by redthing1** [o3o/bindbc-raylib#4]
hello,

I followed your very detailed (thanks!) instructions in the README to build and install raylib from the `3.0.0` tag with RAYGUI support.

however, when i try to run the examples (any example), i get an output that looks like this:
```
Performing "debug" build using /usr/bin/dmd for x86_64.
bindbc-loader 0.3.1: target for configuration "noBC" is up to date.
bindbc-raylib 0.5.0: target for configuration "dynamic" is up to date.
core ~master: building configuration "basic"...
raylib version 300
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./basic_window 
e: 7FFD84267EF0, m:7FFD84267F10
e: 7FFD84267EF0, m:7FFD84267F10
ERROR: badLibrary
```

im not sure what is wrong; i have these files properly installed (looks like a proper shared library):
```
lrwxrwxrwx   16 root 20 Jul 13:03 /usr/local/lib/libraylib.so -> libraylib.so.300
.rwxr-xr-x 1.4M root 20 Jul 13:03 /usr/local/lib/libraylib.so.3.0.0
lrwxrwxrwx   18 root 20 Jul 13:03 /usr/local/lib/libraylib.so.300 -> libraylib.so.3.0.0
```

and it seems like it _is_ finding the library, just something about it is bad? i think i have the right version, because i built the clean `3.0.0` tag.

**Comment by o3o** [comment]
Maybe libraylib isn't  into cache, try:
```
$ ldconfig -p | grep raylib
```
(where `-p` means _Print cache_)

output should be:
```
        libraylib.so.300 (libc6,x86-64) => /usr/lib/libraylib.so.300
	libraylib.so (libc6,x86-64) => /usr/lib/libraylib.so
```
if it is not try:
```
$ sudo ldconfig
```

**Comment by redthing1** [comment]
the command does seem to give the expected output:
```
❯ ldconfig -p | grep raylib
	libraylib.so.300 (libc6,x86-64) => /usr/local/lib/libraylib.so.300
	libraylib.so (libc6,x86-64) => /usr/local/lib/libraylib.so
```

**Comment by o3o** [comment]
Try
```
$ file /usr/lib/libraylib.so.3.0.0 
/usr/lib/libraylib.so.3.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=cf704c1ba99f372865db281888549771724a1bcd, not stripped
```

**Comment by redthing1** [comment]
here is my output (looks correct/matching to me)
```
❯ file /usr/local/lib/libraylib.so.3.0.0
/usr/local/lib/libraylib.so.3.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ebb317833f80ce3bdcb411d5e9a0b00ef20434e6, not stripped
```

**Comment by o3o** [comment]
Yes, seem correct.
the only difference is that your path is `/usr/local/lib/` and my path is `/usr/lib/`

Try to install into `/usr/lib/`
```
$ sudo make install RAYLIB_LIBTYPE=SHARED DESTDIR=/usr
```

**Comment by redthing1** [comment]
I just uninstalled the old libraries, and reinstalled like this, so now it's in `/usr/lib`:
```
❯ ll /usr/lib/libraylib*
lrwxrwxrwx   16 root 22 Jul  0:49 /usr/lib/libraylib.so -> libraylib.so.300
.rwxr-xr-x 1.4M root 22 Jul  0:49 /usr/lib/libraylib.so.3.0.0
lrwxrwxrwx   18 root 22 Jul  0:49 /usr/lib/libraylib.so.300 -> libraylib.so.3.0.0
```

it is still not working. same error as before.

**Comment by o3o** [comment]
Mmmm very strange... let me check

**Comment by o3o** [comment]
I've checked and I've not found errors.
So are you sure you have compiled the right version of raylib?
I mean:
```
$ git checkout -b bindbc 72443f8f
$ git branch
* bindbc
  master
$ git describe --tags
3.0.0-70-g72443f8f
```

**Comment by redthing1** [comment]
Oh, I see the issue. I was building my raylib on the tag `3.0.0`, not on `3.0.0-70-g72443f8f`. I rebuilt it from scratch using that commit as a base, and now it works.
So I think it may just be minor API differences between those versions.
Thank you for helping troubleshoot!
